
package org.ccci.idm.rules.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RuleProvSvcService", targetNamespace = "http://webservice.rules.idm.ccci.org/", wsdlLocation = "http://localhost:8080/rule-based-provisioning-services/rules?wsdl")
public class RuleProvSvcService
    extends Service
{

    private final static URL RULEPROVSVCSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/rule-based-provisioning-services/rules?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        RULEPROVSVCSERVICE_WSDL_LOCATION = url;
    }

    public RuleProvSvcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RuleProvSvcService() {
        super(RULEPROVSVCSERVICE_WSDL_LOCATION, new QName("http://webservice.rules.idm.ccci.org/", "RuleProvSvcService"));
    }

    /**
     * 
     * @return
     *     returns RuleProvSvc
     */
    @WebEndpoint(name = "RuleProvSvcPort")
    public RuleProvSvc getRuleProvSvcPort() {
        return (RuleProvSvc)super.getPort(new QName("http://webservice.rules.idm.ccci.org/", "RuleProvSvcPort"), RuleProvSvc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RuleProvSvc
     */
    @WebEndpoint(name = "RuleProvSvcPort")
    public RuleProvSvc getRuleProvSvcPort(WebServiceFeature... features) {
        return (RuleProvSvc)super.getPort(new QName("http://webservice.rules.idm.ccci.org/", "RuleProvSvcPort"), RuleProvSvc.class, features);
    }

}
