
package org.ccci.idm.rules.staffweb.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "StaffWebRuleProvSvcService", targetNamespace = "http://webservice.rules.idm.ccci.org/", wsdlLocation = "http://localhost:8080/rule-based-provisioning-services/staffweb?wsdl")
public class StaffWebRuleProvSvcService
    extends Service
{

    private final static URL STAFFWEBRULEPROVSVCSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/rule-based-provisioning-services/staffweb?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        STAFFWEBRULEPROVSVCSERVICE_WSDL_LOCATION = url;
    }

    public StaffWebRuleProvSvcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StaffWebRuleProvSvcService() {
        super(STAFFWEBRULEPROVSVCSERVICE_WSDL_LOCATION, new QName("http://webservice.rules.idm.ccci.org/", "StaffWebRuleProvSvcService"));
    }

    /**
     * 
     * @return
     *     returns StaffWebRuleProvSvc
     */
    @WebEndpoint(name = "StaffWebRuleProvSvcPort")
    public StaffWebRuleProvSvc getStaffWebRuleProvSvcPort() {
        return (StaffWebRuleProvSvc)super.getPort(new QName("http://webservice.rules.idm.ccci.org/", "StaffWebRuleProvSvcPort"), StaffWebRuleProvSvc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StaffWebRuleProvSvc
     */
    @WebEndpoint(name = "StaffWebRuleProvSvcPort")
    public StaffWebRuleProvSvc getStaffWebRuleProvSvcPort(WebServiceFeature... features) {
        return (StaffWebRuleProvSvc)super.getPort(new QName("http://webservice.rules.idm.ccci.org/", "StaffWebRuleProvSvcPort"), StaffWebRuleProvSvc.class, features);
    }

}
